### DISCUSSION TITLE
Tunnel a NAS behind CGNAT

### DISCUSSION THREAD

**Discussion by ntn888** [rathole-org/rathole#395] [General]
I'm trying to setup rathole tunnel via a VPS to circumvent my Internet's CG-NAT, and achieve port forwarding. My setup is as follows:

VPS server:
```
services:
  rathole-server:
    restart: unless-stopped
    container_name: rathole-server
    image: archef2000/rathole
    environment:
      - "ADDRESS=0.0.0.0:2333"
      - "DEFAULT_TOKEN=xxxxxxxxxxxxxxxx"
      - "SERVICE_NAME_1=nas_bt"
      - "SERVICE_ADDRESS_1=0.0.0.0:5000"
    ports:
      - 2333:2333
      - 5000:5000
```

NAS (behind NAT):
```
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - WEBUI_PORT=8080
    volumes:
      - /mnt/main/config/qbtorrent:/config
      - /mnt/main/media/torrents:/data/torrents:rw
    network_mode: "service:rathole-client"
    #ports:
      #- 8080:8080		# <== ports cannot be defined, when I issue the above network mode!
      #- 5000:5000
      #- 5000:5000/udp
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped

  rathole-client:
    restart: unless-stopped
    container_name: rathole-client
    image: archef2000/rathole
    command: client
    cap_add:
      - net_admin
    environment:
      - "ADDRESS=xxx.xxx.xxx.xxx:2333"
      - "DEFAULT_TOKEN=xxxxxxxxxxxxxxxx"
      - "SERVICE_NAME_1=nas_bt"
      - "SERVICE_ADDRESS_1=192.168.0.68:5000"
```

I can see that the connection is successfully established to the server:
```
2024-10-17T13:05:31.070429Z  INFO rathole::server: Listening at 0.0.0.0:2333
2024-10-17T13:05:31.070496Z  INFO config_watcher{path="config.toml"}: rathole::config_watcher: Start watching the config
2024-10-17T13:40:25.254802Z  INFO connection{addr=xxx.xxx.xxx.xxx:11003}: rathole::server: Try to handshake a control channel
2024-10-17T13:40:25.574915Z  INFO connection{addr=xxx.xxx.xxx.xxx:11003}: rathole::server: Control channel established service=nas_bt
```

But as you can notice I have no way to access the webUI (locally)..

Thank you.
