### ISSUE TITLE
Dynamic Server Port HA

### ISSUE THREAD

**Issue by vegalou** [rathole-org/rathole#405]
**Feature Proposed**
Replacement of HotReload configuration. Server create work port by 
Token validation & client config.

**Use Case**
Server Cluster provides 100,000+ Traverse-NAT easily.

eg:  A server side only need a simple config like:

```toml
# server.toml
[server]
bind_addr = "0.0.0.0:2333" # `2333` specifies the port that rathole listens for clients
default_token = "use_a_secret_that_only_you_know" 
dynamic_port = 1
```

Each client was told to use specific avaliable server host, work port after hashatged.

```toml
[client]
remote_addr = "example1.com:2333"
default_token = "use_a_secret_that_only_you_know"

[client.services.service1]
dynamic_port = 1
local_addr = "127.0.0.1:554"
server_addr = "8551"
```

via token validation, server could serve

+ example1.com:8551, example1.com:8552, example1.com:8553.....
+ example2.com:8551, example2.com:8552, example2.com:8553.....

Each Client get indivdual server & work port  for Traverse-NAT,
